version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/build:/app/build
      - /app/node_modules
    networks:
      - app_net

  backend:
    build:
      context: ./backend
    ports:
      - "3005:80"
    depends_on:
      - database
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
    networks:
      - app_net
  
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres: